linrongbin16/gitlinker.nvim

lua/gitlinker/git.lua, lua/gitlinker/util.lua
Reverts linrongbin16/gitlinker.nvim#27
=> Revert "refactor: add annotations"

lua/gitlinker/util.lua
=> fix: visual lines

README.md, lua/gitlinker.lua, lua/gitlinker/actions.lua, lua/gitlinker/git.lua, lua/gitlinker/logger.lua, lua/gitlinker/util.lua
=> feat: drop plenary

lua/gitlinker.lua, lua/gitlinker/git.lua
=> refactor(git): rewrite internal API

lua/gitlinker.lua, lua/gitlinker/util.lua
=> perf(logger): reduce logs

README.md
=> docs: wording

README.md, lua/gitlinker.lua, test/deprecated_pattern_rules_minimal_init.lua, test/gitlinker_spec.lua
=> perf(rules): easier pattern rules schema

README.md
=> docs(config): update docs

README.md
=> docs: update highlight group

README.md
=> docs(intro): wording

README.md
=> docs(intro): welcome

README.md
=> docs(config): wording

README.md, lua/gitlinker.lua, lua/gitlinker/actions.lua, lua/gitlinker/git.lua, lua/gitlinker/logger.lua, lua/gitlinker/routers.lua, test/routers_spec.lua
=> feat(blame)!: support more git hosts!

lua/gitlinker/linker.lua
=> fix(parser): support `ssh://git@git.xyz.abc/project/project.git`

README.md
=> docs(config): update use case

README.md
=> chore(docs): update demo

README.md
=> docs(router_types): add current_branch

README.md
=> docs(config): mention branch components

README.md
=> docs(depends): add wslview dependency

README.md
=> docs(badge): add luarocks badge

README.md
=> chore(docs): wording

README.md
=> chore(docs): updates

.github/PULL_REQUEST_TEMPLATE.md
=> chore(template): update PR template

.github/ISSUE_TEMPLATE/bug.md
1. What's the output of `git config --get remote.origin.url`?
It's ...
2. what's the expect git host url you want to generate?
It's ...
3. how do you configure this plugin?
It's ...
=> chore(template): update issue template

README.md
=> docs(mappings): update key mappings

lua/gitlinker/actions.lua, spec/gitlinker/actions_spec.lua, spec/gitlinker/configs_spec.lua, spec/gitlinker/git_spec.lua, spec/gitlinker/highlight_spec.lua, spec/gitlinker/linker_spec.lua, spec/gitlinker/range_spec.lua
=> test(actions): add test cases for 'actions'
