- .github/workflows/ci.yml
> ci(perf): only run conventional commit on 'master' branch

- lua/gitlinker.lua
- lua/gitlinker/git.lua
- lua/gitlinker/logger.lua
- lua/gitlinker/spawn.lua
- lua/gitlinker/util.lua
- test/spawn_spec.lua
> fix(path): resolve symlink in Windows

- README.md
- lua/gitlinker.lua
- lua/gitlinker/highlight.lua
> feat: add highlighting of selected region

- README.md
- lua/gitlinker.lua
> feat(markdown): add '?plain=1' for markdown files to link to code instead of preview

- README.md
- lua/gitlinker.lua
> docs(rules): the 'custom_rules' has higher priority

- README.md
- lua/gitlinker.lua
> feat(rules): add 'override_rules' to override default 'pattern_rules'

- README.md
> docs(config): customize urls in runtime

- README.md
- lua/gitlinker.lua
- lua/gitlinker/routers.lua
- test/routers_spec.lua
> perf(routers): add placeholder to avoid loop call

- README.md
- lua/gitlinker.lua
> break(mapping)!: drop of default key mappings!

- lua/gitlinker.lua
- lua/gitlinker/routers.lua
- test/gitlinker_spec.lua
- test/routers_spec.lua
> refactor(api): hide 'browse'/'blame' api

- README.md
> docs(usage): wording

- lua/gitlinker/actions.lua
I added  an option for using `wslview` command to open url, because wsl does not work with `xdg-open` without custom setting.
This changed file has not been auto-tested, so I tested manually only for  `system` function on may local wsl environment. 
Detail:
1. Copy `system` function definition to clipboard.
1. Open neovim.
1. Paste my neovim command mode like `:lua <copied function body>`.
1. Call function like `:lua system("https://github.com")`.
1. I ensured opening the target page on Windows side browser.
And I did unittests via `vusted` and all green.
If I was needed below them, I will do.
> feat(actions): Add wslview compatible feature

- README.md
> docs(config): optimize config

- lua/gitlinker.lua
- lua/gitlinker/git.lua
- lua/gitlinker/logger.lua
- test/git_spec.lua
- test/logger_spec.lua
> feat(bare/worktree): only check remote branches if remote has 'fetch' config

- README.md
- lua/gitlinker.lua
- test/gitlinker_spec.lua
> feat(config): user router types

- README.md
- lua/gitlinker.lua
- lua/gitlinker/routers.lua
- test/gitlinker_spec.lua
> perf(routers): always add 'plain=1' for github

- lua/gitlinker.lua
> fix(config): fix merged user routers configs

- .luacheckrc
- README.md
- lua/gitlinker.lua
- lua/gitlinker/git.lua
- lua/gitlinker/linker.lua
- test/gitlinker_spec.lua
- test/linker_spec.lua
> feat(branch): provide `DEFAULT_BRANCH` and `CURRENT_BRANCH` components

- README.md
> docs(config): two branch components

- .nvim.lua
- README.md
- lua/gitlinker.lua
- lua/gitlinker/linker.lua
- test.lua
> feat(remote): support multiple remotes (origin/upstream)

- lua/gitlinker.lua
- lua/gitlinker/async.lua
- lua/gitlinker/commons/spawn.lua
- lua/gitlinker/git.lua
- lua/gitlinker/linker.lua
> feat: make link operation non-blocking

- .github/ISSUE_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE.md
1. What's the output of `git config --get remote.origin.url`?
It's ...
2. what's the expect git host url you want to generate?
It's ...
3. how do you configure this plugin?
It's ...
> chore(template): update

- README.md
- lua/gitlinker.lua
> feat(router): add 'default_branch' router type

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- lua/gitlinker/configs.lua
> feat(router): add 'current_branch' router

- .github/workflows/ci.yml
> ci(tag): remove 'auto-tag' action

- README.md
The lazy.nvim install snippets can be improved:
1. `opts = {}` is all you need to setup the plugin, less code
2. It's recommended to add `cmd = "GitLink"` for lazy loading, the plugin will only load when `GitLink` is executed
3. `keys` offers an example (with ruifm's default keymapping) as an example. It will also lazy load the plugin if this keymap is triggered.
> docs: improve lazy install snippet

- README.md
> docs: add mode for lazy keys

- lua/gitlinker/git.lua
- lua/gitlinker/linker.lua
> fix: fix repository root detection

- .github/workflows/ci.yml
- lua/gitlinker/giturlparser.lua
- spec/gitlinker_spec.lua
> fix(url): fix host ends with a colon but port is empty

- .github/workflows/ci.yml
> ci: add code coverage back

- README.md
> docs: add code coverage badge back
